apiVersion: my.domain/v1
kind: WebServer
metadata:
  labels:
    app.kubernetes.io/name: webserver-operator
    app.kubernetes.io/managed-by: kustomize
  name: webserver-sample
spec:
  image: registry.cn-guangzhou.aliyuncs.com/yleoer/nginx
  replicas: 3
