apiVersion: my.domain/v1
kind: WebServer
metadata:
  labels:
    app.kubernetes.io/name: webserver-operator
    app.kubernetes.io/managed-by: kustomize
  name: webserver-sample
spec:
  # TODO(user): Add fields here
